{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "penisgen"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{user.mention}'s penis size is **{math;{length;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{user.discriminator};0;​};1;=};2;==};3;===};4;====};5;=====};6;======};7;=======};8;========};9;=========}}/2} inches** long.\n8{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{user.discriminator};0;​};1;=};2;==};3;===};4;====};5;=====};6;======};7;=======};8;========};9;=========}D",
      "id": "5d657125c33ba00023faa6a9"
    }
  ],
  "formatVersion": "1.1"
}
