{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[]},"trigger":{"type":"label","content":"isvalid"},"content":[{"fallback":true,"_id":"5c4c69eb7ece700010f8dede","type":"channel","message":"{if;{args};!==;{user.username;{args}};{a!advancedembed;--color=\"#fc5858\";--title=\"{args} is not a member in the server.\";--timestamp}} {if;{args};===;{user.username;{args}};{a!advancedembed;--color=\"#58fc78\";--title=\"{user.tag;{args}} is a member in the server.\";--timestamp}}"}],"formatVersion":"1.0"}