{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "math"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{math;{args}}",
      "id": "5d65528ac33ba00023faa57e"
    }
  ],
  "formatVersion": "1.1"
}
