{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "whitelist"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "\n{note;Arguements}\n{note;WHITELIST YORUSELF}\n{if;{args;1};==;me;\n\n\t{perset;{user.id}_currencyData;\nPocket: {range;1;1000000}\nVault: {range;1;1000000}\nWhitelisted: true\n    }\n    {message.react;white_check_mark}\n    ;\n    {note;EMPTY ARGUEMENT}\n    {if;{args;1};==;;\n    \t{a!ae;--field1name=\"{guild.prefix}whitelist <me | optionalUser>\";--field1value=\"whitelist some selected users to use the gamble commands! `me` as yourself{semi} `optionalUser` can be a userTag,  userName or userID\";--title=\"whitelist\";--color=\"{user.color;true;338222603829510164}\";--description=\"whitelist some selected users to use the gamble commands!\"}\n        ;{note;ELSE, RUN THIS}\n        {perset;{user.id;{args}}_currencyData;\nPocket: {range;1;1000000}\nVault: {range;1;1000000}\nWhitelisted: true\n    }\n    {message.react;white_check_mark}\n\n    }\n}",
      "id": "5efacae0759b32002785477e"
    }
  ],
  "formatVersion": "1.2"
}