{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[]},"trigger":{"type":"label","content":"password"},"content":[{"fallback":false,"_id":"5c4705c55339663990b7510e","type":"dm","message":"{a!say;Password generated. Check your direct messages.}{user.send;🔒 **Here is Your Ultra Secure Password:** `{randstr;qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890;{args}}`{set;var;{args}} ({get;var} characters)}"}],"formatVersion":"1.0"}