{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[]},"trigger":{"type":"label","content":"allowaccess"},"content":[{"fallback":true,"_id":"5c4c69eb7ece700010f8dede","type":"channel","message":"{user.removerole;Denied;{args}} {a!advancedembed;--color=\"#67f754\";--icon=\"https://mastertrader.com/wp-content/uploads/2017/06/check-mark-icon.png\";--title=\"User {args} Has Been Allowed Server Access\";--description=\"[Click Here To Check Executed Denied Message](https://discordapp.com/channels/{perget;GUID}/{perget;CHAID}/{perget;MESID})\";--footer=\"Executed By {user.username}\"}"}],"formatVersion":"1.0"}
