{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[]},"trigger":{"type":"label","content":"denyaccess"},"content":[{"fallback":true,"_id":"5c4c69eb7ece700010f8dede","type":"channel","message":"{perset;MESID;{message.id}}{perset;CHAID;{channel.id}}{perset;GUID;{guild.id}}{user.addrole;Denied;{args}} {a!advancedembed;--color=\"#fc4e4e\";--icon=\"https://cdn.iconscout.com/icon/free/png-256/exclamation-mark-outlined-punctuation-red-37950.png\";--title=\"User {args} Has Been Denied Server Access\";--footer=\"Executed By {user.username}\"}"}],"formatVersion":"1.0"}