{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": true
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "keyword",
    "content": " "
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{note;It's advisable to change the variable value below to a channel in your server. This channel is where any notifications are sent as to who triggered the action and what they sent (in an embed, so anything they send is not embedded.)}\n{set;Channel;CHANNEL_NAME_OR_ID_HERE}\n\n{note;This will match any message containing either 'naked' or 'dirty', then '.club', '.vip' or '.site'.}\n\n\n{if;{find;{message.content};(?=.*naked|.*dirty)(.*([.]*)club|.*([.]*)vip|.*([.]*)site).*};!==;;\n  {channel.send;\n    {a!ae;\n        --title=\"Message Content\";\n        --color=\"#fc5255\";\n        --name=\"{user.username}\";\n        --description=\"{message.content}\";\n        --message=\"{user.username} ({user.id}) just posted a potentially dangerous link.\"\n    }\n  ;{get;Channel}}\n  {delete}\n}",
      "id": "5d656105c33ba00023faa5e2"
    }
  ],
  "formatVersion": "1.1"
}
