{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": true,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "color"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{if;{args;1};==;;{a!ae;--field1name=\"Keep in Mind...\";--field1value=\"... a hex code is made of 3 **or** 6 characters that can be letters ranging from A to F and numbers ranging from 0 to 9.\";--title=\"Command Usage\";--description=\"`{guild.prefix}color <hex code>`\";--message=\"Please insert a hex code.\"};{set;hex;{find;{args};^#?([A-Fa-f0-9]{3}|[A-Fa-f0-9]{6})$;1}}{if;{get;hex};==;; {a!ae;--field1name=\"Keep in Mind...\";--field1value=\"... a hex code is made of 3 **or** 6 characters that can be letters ranging from A to F and numbers ranging from 0 to 9.\";--title=\"Command Usage\";--description=\"`{guild.prefix}color <hex code>`\";--message=\"Invalid hex code.\"};{a!ae;--image=\"https://dummyimage.com/500x500/{get;hex}/{get;hex}\";--color=\"#{get;hex}\";--description=\"**Hex Code: __[#{upper;{get;hex}}](http://www.color-hex.com/color/{get;hex})__**\";--footer=\"Requested by {user.tag}\";--footer-icon=\"{user.avatarURL}\"}}}\n",
      "id": "5d5dbd016ea87b0023b1e4ed"
    }
  ],
  "formatVersion": "1.1"
}
