{
  "meta": "Written by Tazeki#9337 in response to JaM's level wrapper failing.",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "level"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{a!ae;--field1name=\"Level\";--field1value=\"{user.level}\";--field1inline;--field2name=\"Experience\";--field2value=\"{math;{user.levelXP}-{user.remainingXP}+{user.nextLevelXP}}/{user.nextLevelXP} | `{math;{user.remainingXP}-{user.nextLevelXP}+{user.levelXP}}` total.\";--field2inline;--field3name=\"Rank\";--field3value=\"[Click Here](https://atlas.bot/leaderboard/{guild.id})\";--field3inline;--icon=\"{user.avatarURL}\";--name=\"{user.username}\"}",
      "id": "60da33a9eaa945873b501f19"
    }
  ],
  "formatVersion": "1.2"
}