{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "level"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{a!ae;--field1name=\"Rank\";--field1value=\"[Click Here](https://atlas.bot/leaderboard/{guild.id})\";--field1inline;--field2name=\"Level\";--field2value=\"{user.level}\";--field2inline;--field3name=\"Experience\";--field3value=\"{find;{math;{user.nextLevelXP}-{user.remainingXP}};(\\d+)\\.?}/{math;{user.nextLevelXP}-{user.levelXP}} • `{math;{utils.calcLevelXP;{user.level}}+{find;{math;{user.nextLevelXP}-{user.remainingXP}};(\\d+)\\.?}}` total\";--field3inline;--icon=\"{user.avatarURL}\";--name=\"{user.username}\"}",
      "id": "5df115bdd4df100023108004"
    }
  ],
  "formatVersion": "1.2"
}