{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "messageCreate",
    "content": null
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{replace;{args};a;ɐ};b;B};c;ɔ};d;p};e;ǝ};f;ɟ};g;ƃ};h;ɥ};i;ı};j;ɾ};k;ʞ};l;ן};m;ɯ};n;u};o;o};p;d};q;b};r;ɹ};s;s};t;ʇ};u;n};v;ʌ};w;ʍ};x;x};y;ʎ};z;z};!;¡};?;¿};_;‾}",
      "channel": null,
      "id": "5d6572d9c33ba00023faa6ba"
    }
  ],
  "formatVersion": "1.1"
}
