{
  "meta": "Exported from https://atlas.bot",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "perval"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{if;{catch;{settings;persistent.length};Error};!==;Error;\n\n{a!ae;\n--title=\"Persistent Storage Keys\";\n--description=\"{replace;{replace;{replace;{replace;{settings;persistent};[[\";{l}perset{semi}};\"]];{r}};\",\";{semi}};\"],[\";{r}\\n{l}perset{semi}}\";\n--footer=\"{settings;persistent.length}/500\"};{channel.send;The server has no saved keys}}",
      "id": "6031a8159104ed002ecb9a60"
    }
  ],
  "formatVersion": "1.2"
}
