{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "location"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{set;LatitudeWhole;{choose;-;}{range;0;90}}{set;LongitudeWhole;{choose;-;}{range;0;180}}\n{set;LatitudeDecimal;{range;0;9999999}}{set;LongitudeDecimal;{range;0;9999999}}\n\nhttps://www.google.com/maps/@{get;LatitudeWhole}.{get;LatitudeDecimal},{get;LongitudeWhole}.{get;LongitudeDecimal},10000m/data=!3m1!1e3",
      "id": "5d65725ac33ba00023faa6b5"
    }
  ],
  "formatVersion": "1.1"
}
