{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[],"permissions":[]},"trigger":{"type":"messageCreate","content":"547046756073078785"},"content":[{"fallback":true,"_id":"5c6b129d277bef0010f92614","type":"channel","message":"{note;BEFORE USING THIS ACTION, CHANGE THE TRIGGER CONTENT TO THE CHANNEL YOU WANNA USE AND RUN THE FOLLOWING COMMAND: \"a!eval {perset;Counting;0}\"}\n\n{if;{args};===;{math;{perget;Counting}+1};{perset;Counting;{math;{perget;Counting}+1}};{delete}}"}],"formatVersion":"1.0"}
