{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[]},"trigger":{"type":"label","content":"location"},"content":[{"fallback":true,"type":"channel","message":"{set;LatitudeWhole;{choose;-;}{range;0;90}}{set;LongitudeWhole;{choose;-;}{range;0;180}}\n{set;LatitudeDecimal;{range;0;9999999}}{set;LongitudeDecimal;{range;0;9999999}}\n\nhttps://www.google.com/maps/@{get;LatitudeWhole}.{get;LatitudeDecimal},{get;LongitudeWhole}.{get;LongitudeDecimal},10000m/data=!3m1!1e3","id":"5c510ef5a2ae2c00176b9f1f"}],"formatVersion":"1.0"}