{"flags":{"ttl":0,"cooldown":0,"enabled":true,"silent":false,"delete":false,"quiet":false},"restrictions":{"mode":"blacklist","roles":[],"channels":[]},"trigger":{"type":"label","content":"recipe"},"content":[{"fallback":true,"_id":"5c4705c55339663990b7512a","type":"channel","message":"{set;ID;{range;1;29000}}{a!advancedembed;--description=\"[Click for your recipe.](http://www.reciperoulette.tv/#{get;ID})\";--footer=\"Recipe ID: {get;ID}\"}"}],"formatVersion":"1.0"}