{
  "meta": "Exported from https://atlas.bot",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "messageCreate",
    "content": null
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{note;The embed that will be sent. Feel free to leave the Title or Message empty.}\n{set;Title;}\n{set;Message;Your_Message_Here}\n{set;Color;#ABC123}\n\n{if;{perget;StickyMessage};===;;\n{perset;StickyMessage;\n{a!ae;--title=\"{get;Title}\";--description=\"{get;Message}\";--color=\"{get;Color}\";--returnId}\n}\n;\n{if;{message.id};!===;{perget;StickyMessage};\n{message.delete;{perget;StickyMessage}}\n{perset;StickyMessage;\n{a!ae;--title=\"{get;Title}\";--description=\"{get;Message}\";--color=\"{get;Color}\";--returnId}\n}\n}}",
      "id": "605b4f669104ed002ed06c60"
    }
  ],
  "formatVersion": "1.2"
}