{
  "meta": "Exported from https://atlas.bot",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": [
      "banMembers"
    ]
  },
  "trigger": {
    "type": "label",
    "content": "tempban"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{set;time;\n{if;{args;2};includes;s;second{if;{find;{args;2};\\d+};!==;1;s}}\n{if;{args;2};includes;m;minute{if;{find;{args;2};\\d+};!==;1;s}}\n{if;{args;2};includes;h;hour{if;{find;{args;2};\\d+};!==;1;s}}\n{if;{args;2};includes;d;day{if;{find;{args;2};\\d+};!==;1;s}}\n{if;{args;2};includes;w;week{if;{find;{args;2};\\d+};!==;1;s}}\n{if;{args;2};includes;y;year{if;{find;{args;2};\\d+};!==;1;s}}}\n\n{if;{args};!==;;\n{if;{catch;{user.id;{args;1}};Error};!==;Error;\n{if;{args;2};!==;;\n{if;{args};includes;--nodm;;\n{catch;\n\n{user.send;You have been temporarily banned from {guild.name} {if;{args;4};!==;;for `{find;{args;2};\\d+} {get;time}` for `{args;4;infinity}`;for `{find;{args;2};\\d+} {get;time}}`.;{user.id;{args;1}}}\n\n\n;{user.username;{args;1}}'s dms are not open, and they were not notifed of the action.}}}}}\n{a!tempban;{args};--nodm}\n{if;{args};includes;--nodm;{channel.send;They were not notified of the action.}}",
      "id": "5fc6b63b77d0ac0026fc7d56"
    }
  ],
  "formatVersion": "1.2"
}