{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": true,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "keyword",
    "content": "sudo"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{set;args;{find;{args};^(?:sudo\\s)(.*)$}}\n{a!say;{get;args}}",
      "id": "5d72b86a21f3e5002364db08"
    }
  ],
  "formatVersion": "1.1"
}
