{
  "meta": "Exported for https://atlasbot.xyz via https://github.com/atlasbot/action-decryptor",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "label",
    "content": "recipe"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{set;ID;{range;1;29000}}{a!advancedembed;--description=\"[Click for your recipe.](http://www.reciperoulette.tv/#{get;ID})\";--footer=\"Recipe ID: {get;ID}\"}",
      "id": "5d65729fc33ba00023faa6b7"
    }
  ],
  "formatVersion": "1.1"
}
